# Generated by Django 3.0.7 on 2020-06-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_title', models.CharField(max_length=200, verbose_name='Заголовок письма')),
                ('celery_text', models.TextField(verbose_name='Описание')),
                ('pub_date', models.DateTimeField(verbose_name='Дата пубдикации')),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spes_name', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст коментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celerylist.Celery')),
            ],
        ),
    ]
